[package]
name = "afetch"
version = "0.0.7"
authors = ["Asthowen<contact@asthowen.fr>", "Squitch1<clement.foure@proton.me>"]
edition = "2024"
rust-version = "1.88.0"
description = "A CLI system information tool written in Rust."
repository = "https://github.com/Asthowen/AFetch"
readme = "README.md"
license = "GPL-3.0"
keywords = ["fetch", "rust"]

[profile.release]
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
lto = true

[profile.release.package."*"]
codegen-units = 1
opt-level = 3
strip = true

[dependencies]
bitcode = "0.6.9"
csscolorparser = "0.8.3"
dirs = "6.0.0"
image = { version = "0.25.10", optional = true }
owo-colors = "4.2.3"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
socket2 = "0.6.3"
starship-battery = "0.11.0"
strip-ansi-escapes = "0.2.1"
strum = { version = "0.28.0", features = ["derive"] }
supports-unicode = "3.0.0"
sysinfo = "0.38.4"
sys-locale = "0.3.2"
unicode-segmentation = "1.13.2"
viuer = { version = "0.11.0", optional = true }
which = "8.0.2"
whoami = { version = "2.1.1", default-features = false, features = ["std"] }

[features]
default = []
image = ["dep:image", "dep:viuer"]
