[package]
name = "afetch"
version = "0.0.7"
authors = ["Asthowen<contact@asthowen.fr>", "Squitch1<clement.foure@proton.me>"]
edition = "2024"
rust-version = "1.88.0"
description = "A CLI system information tool written in Rust."
repository = "https://github.com/Asthowen/AFetch"
readme = "README.md"
license = "GPL-3.0"
keywords = ["fetch", "rust"]

[profile.release]
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
lto = true

[profile.release.package."*"]
codegen-units = 1
opt-level = 3
strip = true

[dependencies]
whoami = { version = "1.5.2", default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
image = { version = "0.25.6", optional = true }
viuer = { version = "0.9.2", optional = true }
unicode-segmentation = "1.12.0"
strip-ansi-escapes = "0.2.1"
starship-battery = "0.10.2"
supports-unicode = "3.0.0"
csscolorparser = "0.7.2"
serde_json = "1.0.143"
sys-locale = "0.3.2"
owo-colors = "4.2.2"
sysinfo = "0.37.0"
bitcode = "0.6.7"
socket2 = "0.6.0"
rayon = "1.11.0"
which = "8.0.0"
dirs = "6.0.0"

[features]
default = []
image = ["dep:image", "dep:viuer"]
