[package]
name = "afetch"
version = "0.0.1"
authors = ["Asthowen<contact@asthowen.fr>"]
edition = "2021"
description = "A CLI system information tool written in Rust."
repository = "https://github.com/Asthowen/AFetch"
readme = "README.md"
license = "GPL-3.0"
keywords = ["fetch", "rust"]

[profile.release]
codegen-units = 1
opt-level = "s"
panic = "abort"
strip = true
lto = true

[dependencies]
colored = { version = "2.0.0", git = "https://github.com/mackwic/colored.git" }
serde = { version = "1.0.159", features = ["derive"] }
serde_yaml = "0.9.19"
sys-locale = "0.2.4"
sysinfo = "0.28.4"
battery = "0.7.8"
minreq = "2.7.0"
whoami = "1.4.0"
image = "0.24.6"
which = "4.4.0"
viuer = "0.6.2"
dirs = "5.0.0"