[package]
name = "afetch"
version = "0.0.1"
authors = ["Asthowen<contact@asthowen.fr>"]
edition = "2021"
description = "AFetch is a simple fetch program written in Rust."
repository = "https://github.com/Asthowen/AFetch"
readme = "README.md"
license = "GPL-3.0"
keywords = ["fetch", "rust"]

[profile.release]
codegen-units = 1
strip = true
lto = true

[dependencies]
yaml-rust = "0.4"
sysinfo = "0.25"
colored = "2.0"
minreq = "2.6"
whoami = "1.2"
which = "4.2"
clap = "3.1"
dirs = "4.0"