[package]
name = "afetch"
version = "0.0.1"
authors = ["Asthowen<contact@asthowen.fr>"]
edition = "2021"
description = "AFetch is a simple fetch program written in Rust."
repository = "https://github.com/Asthowen/AFetch"
readme = "README.md"
license = "GPL-3.0"
keywords = ["fetch", "rust"]

[profile.release]
codegen-units = 1
opt-level = "s"
panic = "abort"
strip = true
lto = true

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.16"
sys-locale = "0.2.3"
sysinfo = "0.27.3"
colored = "2.0.0"
battery = "0.7.8"
minreq = "2.6.0"
whoami = "1.3.0"
image = "0.24.5"
which = "4.3.0"
viuer = "0.6.2"
dirs = "4.0.0"